### ISSUE TITLE
Attempt to read property "id" on null error

### ISSUE THREAD

**Issue by HeadStudios** [Formfeed-UK/nova-dependable-panel#3]
After adding code as below (exceprt)

`BooleanGroup::make('display')->options([
                'email' => 'Email Campaign Fields',
                'landing' => 'Landing Page Fields',
            ])->onlyOnForms(),
            DependablePanel::make('Email Fields', [
            Text::make('Headline', 'headline'),
            Text::make('Subheadline', 'subheadline'),
            ])->separatePanel(true)->dependsOn(['display'], function ($field, $request, $formData) {
                if($formData->display) {
                    $display = json_decode($formData->display);
                    dump("Dumping value of email field");
                    dump($display->landing);
                    if($display->landing === true) {
                        $panel->show();
                    } else {
                        $panel->hide();
                    }
                } else {
                    $panel->hide();
                }
            }),`

I am receiving the error "Attempt to read property on null" when selecting Boolean fields - https://share.getcloudapp.com/Apue9dYL

Full code below:
https://gist.github.com/HeadStudios/fd3dcfc1f11db18fceb4f83590b3cd32

Any input on cause of issue much appreciated.

**Comment by ianrobertsFF** [comment]
Can you show the full stack trace? You can get it from DevTools for the api request if you don't have access anywhere else

**Comment by HeadStudios** [comment]
> Can you show the full stack trace? You can get it from DevTools for the api request if you don't have access anywhere else

Please find below stack trace from laravel.log - let me know if not sufficient:

[2023-01-02 12:45:29] local.ERROR: Attempt to read property "id" on null {"userId":1,"exception":"[object] (ErrorException(code: 0): Attempt to read property \"id\" on null at /home/forge/dev1.rrdevours.monster/app/Nova/Campaign.php:97)
[stacktrace]
#0 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(266): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /home/forge/dev1.rrdevours.monster/app/Nova/Campaign.php(97): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 [internal function]: App\\Nova\\Campaign->App\\Nova\\{closure}()
#3 /home/forge/dev1.rrdevours.monster/vendor/laravel/nova/src/Fields/Field.php(339): call_user_func()
#4 /home/forge/dev1.rrdevours.monster/vendor/laravel/nova/src/Fields/FieldCollection.php(81): Laravel\\Nova\\Fields\\Field->resolve()
#5 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(236): Laravel\\Nova\\Fields\\FieldCollection->Laravel\\Nova\\Fields\\{closure}()
#6 /home/forge/dev1.rrdevours.monster/vendor/laravel/nova/src/Fields/FieldCollection.php(83): Illuminate\\Support\\Collection->each()
#7 /home/forge/dev1.rrdevours.monster/vendor/laravel/nova/src/ResolvesFields.php(430): Laravel\\Nova\\Fields\\FieldCollection->resolve()
#8 /home/forge/dev1.rrdevours.monster/vendor/laravel/nova/src/ResolvesFields.php(356): Laravel\\Nova\\Resource->resolveFields()
#9 /home/forge/dev1.rrdevours.monster/vendor/laravel/nova/src/ResolvesFields.php(381): Laravel\\Nova\\Resource->updateFields()
#10 /home/forge/dev1.rrdevours.monster/vendor/formfeed-uk/nova-subfield-dependson/src/Http/Middleware/InterceptSubfieldDependsOn.php(121): Laravel\\Nova\\Resource->updateFieldsWithinPanels()
#11 /home/forge/dev1.rrdevours.monster/vendor/formfeed-uk/nova-subfield-dependson/src/Http/Middleware/InterceptSubfieldDependsOn.php(125): Formfeed\\SubfieldDependsOn\\Http\\Middleware\\InterceptSubfieldDependsOn->getResourceFields()
#12 /home/forge/dev1.rrdevours.monster/vendor/formfeed-uk/nova-subfield-dependson/src/Http/Middleware/InterceptSubfieldDependsOn.php(48): Formfeed\\SubfieldDependsOn\\Http\\Middleware\\InterceptSubfieldDependsOn->resourceHasSubfields()
#13 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Formfeed\\SubfieldDependsOn\\Http\\Middleware\\InterceptSubfieldDependsOn->handle()
#14 /home/forge/dev1.rrdevours.monster/vendor/formfeed-uk/nova-dependable-panel/src/Http/Middleware/InterceptDisplayFields.php(34): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Formfeed\\DependablePanel\\Http\\Middleware\\InterceptDisplayFields->handle()
#16 /home/forge/dev1.rrdevours.monster/vendor/formfeed-uk/nova-dependable-panel/src/Http/Middleware/InterceptValidationFailure.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Formfeed\\DependablePanel\\Http\\Middleware\\InterceptValidationFailure->handle()
#18 /home/forge/dev1.rrdevours.monster/app/Http/Middleware/CheckMyStriper.php(31): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\CheckMyStriper->handle()
#20 /home/forge/dev1.rrdevours.monster/vendor/laravel/nova/src/Http/Middleware/BootTools.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Nova\\Http\\Middleware\\BootTools->handle()
#22 /home/forge/dev1.rrdevours.monster/vendor/laravel/nova/src/Http/Middleware/DispatchServingNovaEvent.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Nova\\Http\\Middleware\\DispatchServingNovaEvent->handle()
#24 /home/forge/dev1.rrdevours.monster/vendor/inertiajs/inertia-laravel/src/Middleware.php(92): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Inertia\\Middleware->handle()
#26 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#28 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /home/forge/dev1.rrdevours.monster/vendor/laravel/nova/src/Http/Middleware/Authenticate.php(31): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#30 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Nova\\Http\\Middleware\\Authenticate->handle()
#31 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#33 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#35 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#37 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#38 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#40 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#42 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Pipeline\\Pipeline->then()
#44 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack()
#45 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\\Routing\\Router->runRoute()
#46 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute()
#47 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch()
#48 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#49 /home/forge/dev1.rrdevours.monster/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\\DisableBrowserCache->handle()
#51 /home/forge/dev1.rrdevours.monster/vendor/laravel/nova/src/Http/Middleware/ServeNova.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Nova\\Http\\Middleware\\ServeNova->handle()
#53 /home/forge/dev1.rrdevours.monster/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#55 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#57 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#58 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#60 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#61 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#62 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#63 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#64 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#65 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#66 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#67 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#68 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#69 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#70 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then()
#71 /home/forge/dev1.rrdevours.monster/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#72 /home/forge/dev1.rrdevours.monster/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#73 {main}
"} 
[2023-01-02 12:46:03] local.INFO: Received a payload from client {clientId} {"clientId":1204}

**Comment by ianrobertsFF** [comment]
Okay so I can see whats happening, as part of the middleware Dependable Panel will grab your fields from your resource, and check if any fields that use subfields (ie dependable panel) exist, and then resolve the `dependsOn` values correctly for those subfields. As part of this it will use `newResource()` with a blank model (as it doesn't need to hit DB to check this). Your "Link" field on line 96 assumes that (on line 97) the current resource will always have an author that will always have an id.

Just make it : `$this->author?->id` and you should be good.

I'm surprised this hasn't caused issues using regular Nova dependsOn, as IIRC they use `newResource` too ill take a look into how they handle this on their side.

**Comment by HeadStudios** [comment]
UPDATE: Can confirm after removal of DependableField that the following code:

Textarea::make('Excerpt', 'excerpt')->dependsOn(['display'], function ($field, $request, $formData) {
                if($formData->display) {
                    $display = json_decode($formData->display);
                    dump("Dumping value of email field");
                    dump($display->landing);
                    if($display->landing === true) {
                        $field->show();
                    } else {
                        $field->hide();
                    }
                } else {
                    $field->hide();
                }
            }),

Works - not sure if this was due to composer install, being in top in use statement or having it be added above to (unrelated) fields

**Comment by ianrobertsFF** [comment]
> UPDATE: Can confirm after removal of DependableField that the following code:
> 
> Textarea::make('Excerpt', 'excerpt')->dependsOn(['display'], function ($field, $request, $formData) { if($formData->display) { $display = json_decode($formData->display); dump("Dumping value of email field"); dump($display->landing); if($display->landing === true) { $field->show(); } else { $field->hide(); } } else { $field->hide(); } }),
> 
> Works - not sure if this was due to composer install, being in top in use statement or having it be added above to (unrelated) fields

Dependable Field (well its supporting package) was throwing the exception, but it was doing it due to the assumption in your code that the Campaign will always have an author and that the author will always have an ID. 

I'm surprised it didn't throw something (without dependable panel) with your link field as-is on the Create form, as it would be trying to resolve a non-existent relationship then also.

**Comment by HeadStudios** [comment]
Thank you!

**Comment by ianrobertsFF** [comment]
I'll make a couple of small tweaks tomorrow that could mitigate something similar in future, but in general if you're assuming that relationships exist on fields that display on the create form its going to error somewhere. For now you can probably resolve using the change I gave here: https://github.com/Formfeed-UK/nova-dependable-panel/issues/3#issuecomment-1368603192

**Comment by HeadStudios** [comment]
> I'll make a couple of small tweaks tomorrow that could mitigate something similar in future, but in general if you're assuming that relationships exist on fields that display on the create form its going to error somewhere. For now you can probably resolve using the change I gave here: [#3 (comment)](https://github.com/Formfeed-UK/nova-dependable-panel/issues/3#issuecomment-1368603192)

Thank you - that seems like a very straightforward fix and I've made note to attempt my goal with his newfound infomration next time I sit down to code on this issue.

**Comment by HeadStudios** [comment]
P.S. This has been so helpful - you're a life saver - unfortuante that Panels don't have dependsOn in default Nova but I'm glad the Discord community is there to bridge those gaps.

**Comment by HeadStudios** [comment]
I can confirm this issue has been resolved. I should note DependablePanels appear at the end of my resource form fields in the Edit screen even though they are placed at the top within the code. Any input on this before ticket close would be much appreciated specifically if this is expected behavior and if there is any workaround. Thank you!
